services:
  db:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: selmai
      MYSQL_USER: selmai_user
      MYSQL_PASSWORD: selmai_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - selmai-network

  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: selmai
      DB_USER: selmai_user
      DB_PASSWORD: selmai_password
      JWT_SECRET: your-secret-key-here
    networks:
      - selmai-network

  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: always
    environment:
      REACT_APP_API_URL: https://selmai.fr/appli/api
    networks:
      - selmai-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/selmai.fr/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/selmai.fr/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - frontend
      - backend
    networks:
      - selmai-network

volumes:
  mariadb_data:

networks:
  selmai-network:
    driver: bridge