services:
  database:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: selmai
      MYSQL_USER: selmai_user
      MYSQL_PASSWORD: selmai_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - selmai-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: selmai
      DB_USER: selmai_user
      DB_PASSWORD: selmai_password
      JWT_SECRET: your-secret-key-here
    depends_on:
      - database
    networks:
      - selmai-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - selmai-network

volumes:
  mariadb_data:

networks:
  selmai-network:
    driver: bridge